### 코사인 유사도(Cosine Similarity)
- 문장의 유사도를 측정할 때 사용

In [1]:
import numpy as np

In [2]:
v1, v2, v3 = np.array([1, 1, 0]), np.array([2, 1, 0]), np.array([0, 0, 1])
v1_norm = np.sqrt(np.sum(np.square(v1)))
v2_norm = np.sqrt(np.sum(np.square(v2)))
v3_norm = np.sqrt(np.sum(np.square(v3)))
v1_norm, v2_norm, v3_norm

(1.4142135623730951, 2.23606797749979, 1.0)

In [3]:
# v1과 v2의 유사도, v1과 v3의 유사도 
cos12 = np.dot(v1, v2) / (v1_norm * v2_norm)
cos13 = np.dot(v1, v3) / (v1_norm * v3_norm)
cos12, cos13

(0.9486832980505138, 0.0)

In [4]:
def cos_similarity(v1, v2):
    v1_norm = np.sqrt(np.sum(np.square(v1)))
    v2_norm = np.sqrt(np.sum(np.square(v2)))
    return np.dot(v1, v2) / (v1_norm * v2_norm)

- 문장의 코사인 유사도

In [5]:
doc_list = [
    'If you take the blue pill, the story ends',
    'If you take the red pill, you stay in Wonderland',
    'If yout take the red pill, I show you how deep the rabbit hole goes'
]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cvect = CountVectorizer()
doc_cv = cvect.fit_transform(doc_list)
doc_cv.toarray()

array([[1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0],
       [0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 1]],
      dtype=int64)

In [11]:
print(f'문장1 vs 문장2 :, {cos_similarity(doc_cv.toarray()[0], doc_cv.toarray()[1]):.4f}')
print(f'문장1 vs 문장3 :, {cos_similarity(doc_cv.toarray()[0], doc_cv.toarray()[2]):.4f}')
print(f'문장2 vs 문장3 :, {cos_similarity(doc_cv.toarray()[1], doc_cv.toarray()[2]):.4f}')

문장1 vs 문장2 :, 0.6093
문장1 vs 문장3 :, 0.6030
문장2 vs 문장3 :, 0.5774


In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvect = TfidfVectorizer()
doc_tv = tvect.fit_transform(doc_list)
doc_tv.toarray()

array([[0.4155636 , 0.        , 0.4155636 , 0.        , 0.        ,
        0.        , 0.24543856, 0.        , 0.24543856, 0.        ,
        0.        , 0.        , 0.        , 0.4155636 , 0.24543856,
        0.49087711, 0.        , 0.24543856, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.23402865, 0.39624495, 0.23402865, 0.        ,
        0.3013545 , 0.        , 0.39624495, 0.        , 0.23402865,
        0.23402865, 0.39624495, 0.4680573 , 0.        ],
       [0.        , 0.31054974, 0.        , 0.31054974, 0.31054974,
        0.31054974, 0.18341568, 0.        , 0.18341568, 0.31054974,
        0.23618108, 0.31054974, 0.        , 0.        , 0.18341568,
        0.36683136, 0.        , 0.18341568, 0.31054974]])

In [13]:
print(f'문장1 vs 문장2 :, {cos_similarity(doc_tv.toarray()[0], doc_tv.toarray()[1]):.4f}')
print(f'문장1 vs 문장3 :, {cos_similarity(doc_tv.toarray()[0], doc_tv.toarray()[2]):.4f}')
print(f'문장2 vs 문장3 :, {cos_similarity(doc_tv.toarray()[1], doc_tv.toarray()[2]):.4f}')

문장1 vs 문장2 :, 0.4021
문장1 vs 문장3 :, 0.3601
문장2 vs 문장3 :, 0.3716


- Scikit-Learn 코사인 유사도

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([doc_cv.toarray()[0]], [doc_cv.toarray()[1]])

array([[0.6092718]])

In [16]:
cosine_similarity(doc_cv, doc_cv)

array([[1.        , 0.6092718 , 0.60302269],
       [0.6092718 , 1.        , 0.57735027],
       [0.60302269, 0.57735027, 1.        ]])

In [17]:
cosine_similarity(doc_tv)

array([[1.        , 0.40207758, 0.36013824],
       [0.40207758, 1.        , 0.3716459 ],
       [0.36013824, 0.3716459 , 1.        ]])