In [48]:
import numpy as np
import pandas as pd

In [160]:
filename = 'data/melon_song_v2.csv'
plist_filename1 = 'data/melon_playlist1.csv'
plist_filename2 = 'data/melon_playlist2_v2.csv'

In [161]:
df = pd.read_csv(filename)
plist1 = pd.read_csv(plist_filename1)
plist2 = pd.read_csv(plist_filename2)
df.shape, plist1.shape, plist2.shape

((6247, 14), (3845, 5), (60271, 4))

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6247 entries, 0 to 6246
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   songId     6247 non-null   int64 
 1   title      6247 non-null   object
 2   artist     6247 non-null   object
 3   genre      6245 non-null   object
 4   album      6247 non-null   object
 5   lyricist   5849 non-null   object
 6   composer   5845 non-null   object
 7   date       6247 non-null   int64 
 8   img        6247 non-null   object
 9   comment    6247 non-null   int64 
 10  like       6247 non-null   int64 
 11  lyric      6247 non-null   object
 12  plylstSeq  6126 non-null   object
 13  total      6247 non-null   object
dtypes: int64(4), object(10)
memory usage: 683.4+ KB


In [148]:
df.isna().sum()

songId         0
title          0
artist         0
genre          2
album          0
lyricist     398
composer     402
date           0
img            0
comment        0
like           0
lyric          0
plylstSeq    121
total          0
dtype: int64

In [ ]:
df[df.plylstSeq.isna()]

In [ ]:
df.head()

In [8]:
plist2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160459 entries, 0 to 160458
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   plylstSeq  160459 non-null  int64 
 1   songId     160459 non-null  int64 
 2   title      160459 non-null  object
 3   artist     160459 non-null  object
 4   img        160459 non-null  object
dtypes: int64(2), object(3)
memory usage: 6.1+ MB


In [163]:
plist1.plylstSeq = plist1.plylstSeq.astype(str)
plist2.songId = plist2.songId.astype(str)

df.date.fillna(0, inplace=True)
df.date = df.date.astype(int).astype(str)
df.songId = df.songId.astype(str)
df.fillna('', inplace=True)
df.lyric = df.lyric.str.replace('\r', '')
df.head()

songId                      title   artist      genre   
0    418168                         희재      성시경   발라드 국내영화  \
1  35609035                    인생은 뷰티풀      김호중   발라드 국내영화   
2   1046278                      서쪽 하늘      이승철   발라드 국내영화   
3  35609034                        슬픈등      김호중   발라드 국내영화   
4  35728845  고백 (영화 '동감' X 츄 (이달의 소녀))  츄(Chuu)  록/메탈 국내영화   

                       album lyricist composer      date   
0                 국화꽃 향기 OST      양재선      MGR  20030201  \
1              인생은 뷰티풀: 비타돌체      김호중      김호중  20220907   
2                     청연 OST      이승철      윤명선  20051220   
3              인생은 뷰티풀: 비타돌체      김호중      김호중  20220907   
4  고백 (영화 '동감' X 츄 (이달의 소녀))      강현민      강현민  20221016   

                                                 img  comment    like   
0  https://cdnimg.melon.co.kr/cm/album/images/000...      332  138267  \
1  https://cdnimg.melon.co.kr/cm2/album/images/11...      197   17322   
2  https://cdnimg.melon.co.kr/cm/album/images/003...       84   48109   
3  https://cdnimg.melon.co.kr/cm2/album/images/11...      145   15389   
4  https://cdnimg.melon.co.kr/cm2/album/images/11...       80   16902   

                                               lyric            plylstSeq   
0  햇살은 우릴 위해 내리고 \n바람도 서롤 감싸게 했죠 \n우리 웃음속에 계절은 오고...  445029956 411111859  \
1  하나만 알고 둘은\n잘 모르는 사람입니다\n하루는 비틀거리고\n하루는 뒤뚱거리고\n...  457536944 474137187   
2  서쪽하늘로 노을은 지고  \n이젠 슬픔이 돼버린 그대를  \n다시 부를수 없을 것 ...  426571097 405285190   
3  누군가를 다시 만난다면\n여전히 나는 너를\n누군가를 다시 사랑하면\n영원히 나는 ...  457536944 515278519   
4  말해야 하는데 네 앞에 서면\n아무 말 못 하는 내가 미워져\n용기를 내야 해 후회...  484732185 513801514   

                                               total  
0  햇살 우릴 위해 내리다 바람 서 롤 감싸다 하다 우리 웃음 속 계절 오다 또 가다 ...  
1  하나 만 고 둘 자다 모르다 사람 이다 하루 비틀 거리 고 하루 뒤뚱거리 고 월요일...  
2  서쪽하늘 노을 지고 젠 슬픔 돼다 버리다 그대 다시 부르다 없다 같다 또 한번 불다...  
3  누군가 다시 만나다 여전하다 나 너 누군가 다시 사랑 하다 영원하다 나 너 다시 또...  
4  말 하다 하다 네 앞 서면 아무 말 못 하다 내 가 미우다 용기 내야 해 후회 하다...

In [8]:
plist2.head()

songId                          title        artist   
0  33213267                      Love Song  Why Don't We  \
1  32544401              Ghost In A Flower     Yorushika   
2  33502105                   Every Second    Mina Okabe   
3  33469725  Loving You Girl (Feat. Hkeem)   Peder Elias   
4  32464068                        SKYLINE           김세정   

                                                 img  
0  https://cdnimg.melon.co.kr/cm2/album/images/10...  
1  https://cdnimg.melon.co.kr/cm2/album/images/10...  
2  https://cdnimg.melon.co.kr/cm2/album/images/10...  
3  https://cdnimg.melon.co.kr/cm2/album/images/10...  
4  https://cdnimg.melon.co.kr/cm2/album/images/10...

In [36]:
# plist2 = plist2[['songId', 'title', 'artist', 'img']]
# print(plist2.shape, plist2.songId.nunique())
# plist2.drop_duplicates(subset=['songId'], inplace=True)
# print(plist2.shape, plist2.songId.nunique())
# plist2.head()


(60271, 4) 60271
(60271, 4) 60271


songId                          title        artist   
0  33213267                      Love Song  Why Don't We  \
1  32544401              Ghost In A Flower     Yorushika   
2  33502105                   Every Second    Mina Okabe   
3  33469725  Loving You Girl (Feat. Hkeem)   Peder Elias   
4  32464068                        SKYLINE           김세정   

                                                 img  
0  https://cdnimg.melon.co.kr/cm2/album/images/10...  
1  https://cdnimg.melon.co.kr/cm2/album/images/10...  
2  https://cdnimg.melon.co.kr/cm2/album/images/10...  
3  https://cdnimg.melon.co.kr/cm2/album/images/10...  
4  https://cdnimg.melon.co.kr/cm2/album/images/10...

In [12]:
# melon_song에 들어있는 songId가 플레이리스트에 포함되어 있는 수
# 60271 - 5947 = 54324 개의 노래는 melon_song 데이터에 없다.
# df_song_list = df.songId.values
# plist2[plist2.songId.isin(df_song_list)].shape

(5947, 4)

### 1. 찾을 노래 제목과 아티스트 입력 받기

In [164]:
# 키워드 바꿔가면서 찾아보기
import string, re
print(string.punctuation)

# 에잇(Prod.&Feat. SUGA of BTS)
# 아이유


keyword_artist = '송이한'
keyword_title = '아무 일도, 아무것도'
keyword_title = re.sub('['+string.punctuation+']', '', keyword_title)
keyword_artist = re.sub('['+string.punctuation+']', '', keyword_artist)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [151]:
# keyword_title = keyword_title.replace(' ', '|')
# keyword_artist = keyword_artist.replace(' ', '&')
print(keyword_title, keyword_artist)

아무 일도 아무것도 송이한


In [47]:
names = ['jack', 'bob', 'WAT.SON', 'jake', 'mike', 'don', 'george', 'natasha', 'jill', 'ann', 'JOHN\'', 'johnSON']
print(names)
# ser = pd.Series(names)
ser = pd.DataFrame(names, columns=['ser'])

keyword = 'SO.N'.lower()
keyword = re.sub('['+string.punctuation+']', '', keyword)
print(keyword)

ser[ser.ser.str.lower().str.replace('['+string.punctuation+']','').str.contains(keyword)]

['jack', 'bob', 'WAT.SON', 'jake', 'mike', 'don', 'george', 'natasha', 'jill', 'ann', "JOHN'", 'johnSON']
son


ser
2   WAT.SON
11  johnSON

In [165]:
# 노래 제목과 가수로 찾기
songIds = df[df.title.str.replace('['+string.punctuation+']','', regex=True).str.contains(keyword_title, case=False)
              & df.artist.str.replace('['+string.punctuation+']','', regex=True).str.contains(keyword_artist, case=False)]
songIds

songId        title artist     genre                             album   
53   35561629  아무 일도, 아무것도    송이한  발라드 국내영화  아무 일도, 아무것도 (뷰티풀 모먼트 OST 스페셜 트랙)  \
234  35725437  아무 일도, 아무것도    송이한  발라드 국내영화                       뷰티풀 모먼트 OST   

    lyricist composer      date   
53       이기환      이기환  20220828  \
234      이기환      이기환  20221014   

                                                   img  comment  like   
53   https://cdnimg.melon.co.kr/cm2/album/images/11...        2  1100  \
234  https://cdnimg.melon.co.kr/cm2/album/images/11...        0    49   

                                                 lyric            plylstSeq   
53   따듯했던 그날 속에 우리는\n차가워진 흔적들로 남아\n지우려 하면 할수록 다시\n반...  401004189 500439113  \
234  따듯했던 그날 속에 우리는\n차가워진 흔적들로 남아\n지우려 하면 할수록 다시\n반...                        

                                                 total  
53   따다 하다 그날 속 우리 차가워지다 흔적 남아 지우다 하다 하다 다시 반복 되다 아...  
234  따다 하다 그날 속 우리 차가워지다 흔적 남아 지우다 하다 하다 다시 반복 되다 아...

In [212]:
# 첫번째 songId로 검색해 보기 위해(원하는 것은 사용자가 선택하도록)
songId = songIds.songId.values[0]
songIds


songId        title artist     genre                             album   
53   35561629  아무 일도, 아무것도    송이한  발라드 국내영화  아무 일도, 아무것도 (뷰티풀 모먼트 OST 스페셜 트랙)  \
234  35725437  아무 일도, 아무것도    송이한  발라드 국내영화                       뷰티풀 모먼트 OST   

    lyricist composer      date   
53       이기환      이기환  20220828  \
234      이기환      이기환  20221014   

                                                   img  comment  like   
53   https://cdnimg.melon.co.kr/cm2/album/images/11...        2  1100  \
234  https://cdnimg.melon.co.kr/cm2/album/images/11...        0    49   

                                                 lyric            plylstSeq   
53   따듯했던 그날 속에 우리는\n차가워진 흔적들로 남아\n지우려 하면 할수록 다시\n반...  401004189 500439113  \
234  따듯했던 그날 속에 우리는\n차가워진 흔적들로 남아\n지우려 하면 할수록 다시\n반...                        

                                                 total  
53   따다 하다 그날 속 우리 차가워지다 흔적 남아 지우다 하다 하다 다시 반복 되다 아...  
234  따다 하다 그날 속 우리 차가워지다 흔적 남아 지우다 하다 하다 다시 반복 되다 아...

45      36242042 35645694 34826873 34164058 35456806 3...
84      32653631 34100776 33428837 32159598 33766984 3...
109     31587557 32935092 32476250 30017614 30269908 2...
122     32961285 30657307 36136158 35944239 31624517 3...
124     31143991 32497863 33369437 35867428 36081382 3...
                              ...                        
3728    33175764 33362590 8298724 33780124 32939043 33...
3735    30636089 33043504 3780500 32613630 33406558 32...
3782    35411219 34055256 35564570 30099930 32626719 3...
3784    36414841 36421592 34557377 33271276 36136158 3...
3831    8036156 34055256 31674786 33680289 31496488 35...
Name: songIds, Length: 144, dtype: object


In [34]:
a = np.array([1, 2, 6, 4, 2, 3, 2, 6, 6, 4])
u, indices = np.unique(a, return_counts=True)
re_indices = np.argsort(-indices)

print(u[re_indices])
print(indices[re_indices])

print(u)
print(indices)


[2 6 4 1 3]
[3 3 2 1 1]
[1 2 3 4 6]
[1 3 1 2 3]


In [215]:
# 가장 많이 들어간 tag 찾기
tags = np.unique(' '.join(plist1[plist1.songIds.str.contains(songId)]['tag'].values).split(), return_counts=True)

In [216]:
print(len(tags[0]))

22


In [178]:
genre = df[df.songId == songId].genre.values[0]
genre

'발라드 국내영화'

In [220]:

# argsort : 값이 큰 순서대로 값의 인덱스 정렬 -1 큰 순서대로
str_tags = ''
if len(tags[0]):
    re_count = np.argsort(-tags[1]) 
    if len(re_count) > 2:
        str_tags = f"{tags[0][re_count][0].strip('#')}, {tags[0][re_count][1].strip('#')} 그리고 {tags[0][re_count][2].strip('#')}"

print(str_tags)

발라드, 이별 그리고 감성


In [81]:
df_tags = pd.DataFrame({'tag' : tags[0], 'count' : tags[1]})
df_tags.head()

tag  count
0        #1975      1
1      #2000년대      1
2  #2000년대여름노래      1
3       #2010년      1
4        #2021      2

In [82]:
str_tags = ' '.join(df_tags.sort_values('count', ascending=False).head(2)['tag'])
str_tags

'#기분전환 #감성'

In [91]:
print( ' '.join(plist1[plist1.songIds.str.contains(songId)]['songIds'].values))

36242042 35645694 34826873 34164058 35456806 33055519 34052587 33743290 8298724 33903923 32142762 33597153 33880120 34172221 33805294 30644500 7967351 30656620 7942948 31196872 30623495 31939062 32057583 31261006 30290580 31283160 30038185 9600435 5379383 638570 32653631 34100776 33428837 32159598 33766984 32158763 31409519 33248740 34588190 30303507 30688507 33315260 31387744 31668320 32325553 31441820 32514163 35536571 34562040 32265694 33320444 35268790 31871019 33842207 31445544 32226455 34497207 31131497 33214330 32650472 32539996 32479614 31843404 32141931 31584885 34521607 32409057 31864770 35197785 33722788 33388143 32961284 32574156 33150797 35527352 34558245 34100775 32275003 31441818 32939090 31587557 32935092 32476250 30017614 30269908 2939095 4420983 4824874 4019174 5464978 30006916 5459423 4252730 4252732 30636089 33013877 33503722 608212 32961285 30657307 36136158 35944239 31624517 34927767 35757422 34101834 33425484 35944240 33369437 33425478 35488206 34101837 34562040 

In [208]:
# 플레이리스트에서 songIds 값들을 합쳐 자기자신은 지우고 리스트로 분리
# 가장 많이 들어가 songId 찾기
songs = np.unique(' '.join(plist1[plist1.songIds.str.contains(songId)]['songIds'].values).replace(songId+' ', '').split(), return_counts=True)
songs

(array([], dtype=float64), array([], dtype=int64))

In [143]:
not df[df.songId == '32939000'].empty

False

In [206]:
cnt = 0
song_list = []

# argsort 값을 sort해서 값의 index를 오름차순으로 '-' 해주면 내림차순으로
for s_id in songs[0][np.argsort(-songs[1])]:    
    if not df[df.songId.isin([s_id])].empty :
        cnt += 1
        song_list.append(s_id)
    if cnt == 5 : break

print(song_list)



[]


In [116]:

if len(songs[0]) > 5:
    re_count = np.argsort(-songs[1])
    song_list = songs[0][re_count][:20]
else:
    song_list = songs[0]

In [109]:
df_songs = pd.DataFrame({'songId' : songs[0], 'count' : songs[1]})
df_songs

songId  count
0     1002911      1
1     1010331      1
2       10124      1
3       10126      2
4     1017063      1
...       ...    ...
4529   983662      1
4530   984030      1
4531   985739      1
4532   987651      1
4533   997464      1

[4534 rows x 2 columns]

In [110]:
song_list = df_songs.sort_values('count', ascending=False).head(10)
song_list

songId  count
339    2939095     27
2007  32939042     21
2011  32939046     14
2001  32939001     12
2000  32939000     12
2763  34476749     12
3272  35944240     12
3194  35757422     11
3271  35944239     11
2639  34055256     11

In [113]:
song_list

array(['2939095', '32939042', '32939046', '32939001', '32939000',
       '34476749', '35944240', '34055256', '33369437', '35757422'],
      dtype='<U12')

In [114]:
df[df.songId.isin(song_list)][['songId', 'title', 'artist', 'genre',]]

songId               title                     artist        genre
4588  32939046  여기저기거기 (Feat. 수퍼비)                         범키     R&B/Soul
4896  34055256           김철수 씨 이야기                        허회경  인디음악 포크/블루스
4926   2939095               널 생각해  원 모어 찬스 (one more chance)  인디음악 포크/블루스
4994  32939042            아침만 남겨주고                        김현창  인디음악 포크/블루스

In [205]:
# 해당 songId 들 정보 출력
# 나중에 to_dict()로 반환
# 없으면 플레이리스트2에 있는 songId 에서 정보 가져오기
tmp = df[df.songId.isin(song_list)][['songId', 'title', 'artist', 'genre', 'album', 'lyricist', 'composer']]
if tmp.empty:
    tmp = plist2[plist2.songId.isin(song_list)]
tmp

Empty DataFrame
Columns: [songId, title, artist, img]
Index: []