In [1]:
import numpy as np
import pandas as pd

In [67]:
filename = 'data/melon_song_v3.csv'
plist_filename1 = 'data/melon_playlist1.csv'
plist_filename2 = 'data/melon_playlist2_v2.csv'

In [68]:
df = pd.read_csv(filename)
plist1 = pd.read_csv(plist_filename1)
plist2 = pd.read_csv(plist_filename2)
df.shape, plist1.shape, plist2.shape

((6247, 15), (3845, 5), (60271, 4))

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6247 entries, 0 to 6246
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   songId     6247 non-null   int64 
 1   title      6247 non-null   object
 2   artist     6247 non-null   object
 3   genre      6245 non-null   object
 4   album      6247 non-null   object
 5   lyricist   5849 non-null   object
 6   composer   5845 non-null   object
 7   date       6247 non-null   int64 
 8   img        6247 non-null   object
 9   comment    6247 non-null   int64 
 10  like       6247 non-null   int64 
 11  lyric      6247 non-null   object
 12  plylstSeq  6126 non-null   object
 13  total      6247 non-null   object
dtypes: int64(4), object(10)
memory usage: 683.4+ KB


In [148]:
df.isna().sum()

songId         0
title          0
artist         0
genre          2
album          0
lyricist     398
composer     402
date           0
img            0
comment        0
like           0
lyric          0
plylstSeq    121
total          0
dtype: int64

In [69]:
df[df.plylstSeq.isna()].title.values

array(['이럴거면', '아무 일도, 아무것도', '오후 (Satellite)', '드림 (Dream) (Inst.)',
       '마지막 질주', '마이럽럽', '퐁당퐁당', 'Love Love', '날 따라 해봐요', '아빠의 잔소리', '점프',
       '엄마도 말야', '힘내 응원해', '내 이름은', '파라다이스', '목욕 가는 길', '날 따라 해봐요',
       '슈퍼파워', '슈퍼스타', '새마음 운동', '하트하트', '숨바꼭질', '괜찮아 괜찮아', '파도타기',
       '엄마의 이름', '내 팬티', '나는 소파!', '장장장 장수탕', '발냄새', '나랑 같이 놀래?',
       '은밀하게 위대하게', '혼자 있을 때 들리는 소리', '안녕 안녕', '동동동 구리구리 동동', '쓰담쓰담',
       '우리는 오늘도 장수탕', '냉탕놀이 2', '평범한 나라 평범한 집 평범한 나', '오늘은 생일파티',
       '냉탕놀이 1', '아기 상어의 생일', '얼음땡', '세상의 모든 때여 (때밀이송)', '해적의 황금시대',
       '아픈만큼 쑥 커라', '해초 스웩 (아기상어 올리와 윌리엄)', '신비로운 연못 (선녀송)',
       '오싹오싹 바닷속 괴물', '안녕 (생일파티 ver.)', '아기상어 리믹스 (앙코르)',
       'Best Kept Secret', '돌아갈 그 날까지', '스텔라마리스', '질투하라',
       'Love at first sight', 'Are You There?', '팝팝 키즈팝', '산호 놀이터로 모여라',
       '울새와의 하루', '집에 가는 길', '혼자 서는 법', '우리 마을에서 가장 잘 생긴 사람', 'Epiphany',
       '바닷속 행진', '괴물이 나타났다!', '팅팅탱탱 리듬파티', '항해일지', 'Ever After', 'One',
       'Role OF A Lifetime', 'Bare', '녹의 흔적', '상어 가족

In [ ]:
df.head()

In [8]:
plist2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160459 entries, 0 to 160458
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   plylstSeq  160459 non-null  int64 
 1   songId     160459 non-null  int64 
 2   title      160459 non-null  object
 3   artist     160459 non-null  object
 4   img        160459 non-null  object
dtypes: int64(2), object(3)
memory usage: 6.1+ MB


In [70]:
plist1.plylstSeq = plist1.plylstSeq.astype(str)
plist2.songId = plist2.songId.astype(str)
df.songId = df.songId.astype(str)
df.fillna('', inplace=True)
df.lyric = df.lyric.str.replace('\r', '')
df.head(1)

songId title artist     genre       album lyricist composer      date  \
0  418168    희재    성시경  발라드 국내영화  국화꽃 향기 OST      양재선      MGR  20030201   

                                                 img  comment    like  \
0  https://cdnimg.melon.co.kr/cm/album/images/000...      332  138267   

                                               lyric            plylstSeq  \
0  햇살은 우릴 위해 내리고 \n바람도 서롤 감싸게 했죠 \n우리 웃음속에 계절은 오고...  445029956 411111859   

                                               total  \
0  햇살 우릴 위해 내리다 바람 서 롤 감싸다 하다 우리 웃음 속 계절 오다 또 가다 ...   

                    ly_summary  
0  정말로 울면 내가 그댈 보내 <br>준 것 같아서

In [7]:
plist2.head()

songId                          title        artist  \
0  33213267                      Love Song  Why Don't We   
1  32544401              Ghost In A Flower     Yorushika   
2  33502105                   Every Second    Mina Okabe   
3  33469725  Loving You Girl (Feat. Hkeem)   Peder Elias   
4  32464068                        SKYLINE           김세정   

                                                 img  
0  https://cdnimg.melon.co.kr/cm2/album/images/10...  
1  https://cdnimg.melon.co.kr/cm2/album/images/10...  
2  https://cdnimg.melon.co.kr/cm2/album/images/10...  
3  https://cdnimg.melon.co.kr/cm2/album/images/10...  
4  https://cdnimg.melon.co.kr/cm2/album/images/10...

In [36]:
# plist2 = plist2[['songId', 'title', 'artist', 'img']]
# print(plist2.shape, plist2.songId.nunique())
# plist2.drop_duplicates(subset=['songId'], inplace=True)
# print(plist2.shape, plist2.songId.nunique())
# plist2.head()


(60271, 4) 60271
(60271, 4) 60271


songId                          title        artist   
0  33213267                      Love Song  Why Don't We  \
1  32544401              Ghost In A Flower     Yorushika   
2  33502105                   Every Second    Mina Okabe   
3  33469725  Loving You Girl (Feat. Hkeem)   Peder Elias   
4  32464068                        SKYLINE           김세정   

                                                 img  
0  https://cdnimg.melon.co.kr/cm2/album/images/10...  
1  https://cdnimg.melon.co.kr/cm2/album/images/10...  
2  https://cdnimg.melon.co.kr/cm2/album/images/10...  
3  https://cdnimg.melon.co.kr/cm2/album/images/10...  
4  https://cdnimg.melon.co.kr/cm2/album/images/10...

In [12]:
# melon_song에 들어있는 songId가 플레이리스트에 포함되어 있는 수
# 60271 - 5947 = 54324 개의 노래는 melon_song 데이터에 없다.
# df_song_list = df.songId.values
# plist2[plist2.songId.isin(df_song_list)].shape

(5947, 4)

### 1. 찾을 노래 제목과 아티스트 입력 받기

In [71]:
# 키워드 바꿔가면서 찾아보기
import string, re
print(string.punctuation)

# 에잇(Prod.&Feat. SUGA of BTS)
# 아이유


keyword_artist = ''
keyword_title = '다섯계절이야기'
keyword_title = re.sub('['+string.punctuation+']', '', keyword_title)
keyword_artist = re.sub('['+string.punctuation+']', '', keyword_artist)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [72]:
# keyword_title = keyword_title.replace(' ', '|')
# keyword_artist = keyword_artist.replace(' ', '&')
print(keyword_title, keyword_artist)

다섯계절이야기 


In [47]:
names = ['jack', 'bob', 'WAT.SON', 'jake', 'mike', 'don', 'george', 'natasha', 'jill', 'ann', 'JOHN\'', 'johnSON']
print(names)
# ser = pd.Series(names)
ser = pd.DataFrame(names, columns=['ser'])

keyword = 'SO.N'.lower()
keyword = re.sub('['+string.punctuation+']', '', keyword)
print(keyword)

ser[ser.ser.str.lower().str.replace('['+string.punctuation+']','').str.contains(keyword)]

['jack', 'bob', 'WAT.SON', 'jake', 'mike', 'don', 'george', 'natasha', 'jill', 'ann', "JOHN'", 'johnSON']
son


ser
2   WAT.SON
11  johnSON

In [81]:
# 노래 제목과 가수로 찾기
songIds = df[df.title.str.replace('['+string.punctuation+']','', regex=True).str.contains(keyword_title, case=False)
              & df.artist.str.replace('['+string.punctuation+']','', regex=True).str.contains(keyword_artist, case=False)]
songIds.songId

6148    3515505
Name: songId, dtype: object

In [82]:
# 첫번째 songId로 검색해 보기 위해(원하는 것은 사용자가 선택하도록)
songId = songIds.songId.values[0]
# songIds


45      36242042 35645694 34826873 34164058 35456806 3...
84      32653631 34100776 33428837 32159598 33766984 3...
109     31587557 32935092 32476250 30017614 30269908 2...
122     32961285 30657307 36136158 35944239 31624517 3...
124     31143991 32497863 33369437 35867428 36081382 3...
                              ...                        
3728    33175764 33362590 8298724 33780124 32939043 33...
3735    30636089 33043504 3780500 32613630 33406558 32...
3782    35411219 34055256 35564570 30099930 32626719 3...
3784    36414841 36421592 34557377 33271276 36136158 3...
3831    8036156 34055256 31674786 33680289 31496488 35...
Name: songIds, Length: 144, dtype: object


In [34]:
a = np.array([1, 2, 6, 4, 2, 3, 2, 6, 6, 4])
u, indices = np.unique(a, return_counts=True)
re_indices = np.argsort(-indices)

print(u[re_indices])
print(indices[re_indices])

print(u)
print(indices)


[2 6 4 1 3]
[3 3 2 1 1]
[1 2 3 4 6]
[1 3 1 2 3]


In [83]:
# 가장 많이 들어간 tag 찾기
tags = np.unique(' '.join(plist1[plist1.songIds.str.contains(songId)]['tag'].values).split(), return_counts=True)
print(len(tags[0]))

10


In [84]:
genre = df[df.songId == songId].genre.values[0]
genre

'포크/블루스'

In [85]:

# argsort : 값이 큰 순서대로 값의 인덱스 정렬 -1 큰 순서대로
if len(tags[0]) :
    re_count = np.argsort(-tags[1]) 
    if len(re_count) > 2:
        pro_tags = f"{tags[0][re_count][0]}, {tags[0][re_count][1]} 그리고 {tags[0][re_count][2].strip('#')}"
    elif len(re_count) == 2:
        pro_tags = f"{tags[0][re_count][0]} 그리고 {tags[0][re_count][1]}"
    else:
        pro_tags = f"{tags[0][re_count][0]}"

else:
    pro_tags = ''

pro_tags

'#RESTINPAST, #그루브 그리고 내적댄스'

In [38]:
print( ' '.join(plist1[plist1.songIds.str.contains(songId)]['songIds'].values))

In [90]:
# 플레이리스트에서 songIds 값들을 합쳐 자기자신은 지우고 리스트로 분리
# 가장 많이 들어가 songId 찾기
songs = np.unique(' '.join(plist1[plist1.songIds.str.contains(songId)]['songIds'].values).replace(songId+' ', '').split(), return_counts=True)
songs[0]

array(['31204359', '31429071', '31869526', '32147288', '32364282',
       '32600616', '32789925', '33164469', '33164486', '33363290',
       '34067967', '34067968', '34748228', '34752692', '34847096',
       '34869357', '35002694', '35002695', '35002698', '35010454',
       '35155056', '35196772', '35327786', '35444525', '35456563',
       '35487612', '35540853', '35582017', '35582558', '35689779',
       '35727874', '35779412', '35781705', '35781710', '35891577',
       '35891601', '35919156', '35956164', '35956165', '35987313'],
      dtype='<U8')

In [91]:
plist2[plist2.songId.isin(songs[0])]

songId                                              title  \
16249  33164486                                                Sky   
55798  35002698                                  PUFFIN ON ZOOTIEZ   
56708  35891601                      Superhero (Heroes & Villains)   
60124  32364282                                             Reborn   
60125  35987313                                     Maya Freestyle   
60126  35956165                                    Neo (feat. 072)   
60127  35956164                                  Umm (feat. Odd95)   
60128  34067967                                         Way Bigger   
60129  34067968                 Flocky Flocky (feat. Travis Scott)   
60130  32600616                                 Hard To Choose One   
60131  32789925                               GREECE (Feat. Drake)   
60132  35919156                                       32 Freestyle   
60133  35891577                                           Overdose   
60134  34748228                           Petty Too (Feat. Future)   
60135  34752692                                             Crypto   
60136  35002694                                              712PM   
60137  35727874                             G Nikes (Feat. Polo G)   
60138  33363290  Moonwalking in Calabasas (Remix) (Feat. Blueface)   
60139  35781705                                                New   
60140  35689779                                    Nothing Changed   
60141  35196772                           HOTEL LOBBY (Unc & Phew)   
60142  35781710                                                  X   
60143  33164469                                     Stop Breathing   
60144  32147288                              Big (Feat. Lil Gotit)   
60145  34869357              BIG PURR (Prrdd) (Feat. Pooh Shiesty)   
60146  31869526                   Real Hood Baby (feat. Stickbaby)   
60147  35582558                                              Detox   
60148  35002695                                      I'M DAT N****   
60149  35582017                                               Talk   
60150  35779412                     Ain't Safe (Feat. Don Toliver)   
60151  35540853                     BUST IT (Feat. UNEDUCATED KID)   
60152  31429071                                             Fetish   
60153  35487612                                      Slide (Remix)   
60154  34847096                              Waddup (Feat. Polo G)   
60155  35444525                                         Big Steppa   
60156  35456563                     Pressurelicious (feat. Future)   
60157  35327786                        Dangerous (Feat. Ak2daface)   
60158  35010454            I Don't Deserve That Cap (Feat. BSlime)   
60159  35155056                                             Turban   
60160  31204359                                      Drip or Drown   

                                  artist  \
16249                      Playboi Carti   
55798                             Future   
56708  Metro Boomin, Future, Chris Brown   
60124                     UNEDUCATED KID   
60125                                 J4   
60126                                JOo   
60127                                JOo   
60128                        Don Toliver   
60129                        Don Toliver   
60130                             Future   
60131                          DJ Khaled   
60132                          BabyDrill   
60133                      Finesse2tymes   
60134                           Lil Durk   
60135              Takeoff, Rich The Kid   
60136                             Future   
60137                         Nardo Wick   
60138                                DDG   
60139                         Ken Carson   
60140                     Quavo, Takeoff   
60141                     Quavo, Takeoff   
60142                         Ken Carson   
60143                      Playboi Carti   
60144                          Coi Leray   
60145                          Coi Ler

In [87]:
cnt = 0
song_list = []

df_songs = pd.DataFrame()
# argsort 값을 sort해서 값의 index를 오름차순으로 '-' 해주면 내림차순으로
for s_id in songs[0][np.argsort(-songs[1])]:    
    tmp = df[df.songId.isin([s_id])][['songId', 'title', 'artist', 'img']]
    if not tmp.empty :
        cnt += 1
        df_songs = pd.concat([df_songs, tmp])
    else:
        tmp = plist2[plist2.songId.isin([s_id])]
        if not tmp.empty:
            cnt += 1
            df_songs = pd.concat([df_songs, tmp])

    if cnt == 5 : break

df_songs



songId                           title               artist  \
60160  31204359                   Drip or Drown                Gunna   
60157  35327786     Dangerous (Feat. Ak2daface)  Chillin Homie, KHAN   
60155  35444525                      Big Steppa            Flo Milli   
60156  35456563  Pressurelicious (feat. Future)  Megan Thee Stallion   
60153  35487612                   Slide (Remix)  Madmarcc, 21 Savage   

                                                     img  
60160  https://cdnimg.melon.co.kr/cm/album/images/101...  
60157  https://cdnimg.melon.co.kr/cm2/album/images/10...  
60155  https://cdnimg.melon.co.kr/cm2/album/images/11...  
60156  https://cdnimg.melon.co.kr/cm2/album/images/11...  
60153  https://cdnimg.melon.co.kr/cm2/album/images/11...

In [29]:
pro_psongs = df[df.songId.isin(song_list)][['songId', 'title', 'artist', 'img']]

if pro_psongs.empty:
    pro_psongs = plist2[plist2.songId.isin(song_list)]

pro_psongs = pro_psongs.to_dict('records')
pro_psongs


[]

In [116]:

if len(songs[0]) > 5:
    re_count = np.argsort(-songs[1])
    song_list = songs[0][re_count][:20]
else:
    song_list = songs[0]

In [109]:
df_songs = pd.DataFrame({'songId' : songs[0], 'count' : songs[1]})
df_songs

songId  count
0     1002911      1
1     1010331      1
2       10124      1
3       10126      2
4     1017063      1
...       ...    ...
4529   983662      1
4530   984030      1
4531   985739      1
4532   987651      1
4533   997464      1

[4534 rows x 2 columns]

In [110]:
song_list = df_songs.sort_values('count', ascending=False).head(10)
song_list

songId  count
339    2939095     27
2007  32939042     21
2011  32939046     14
2001  32939001     12
2000  32939000     12
2763  34476749     12
3272  35944240     12
3194  35757422     11
3271  35944239     11
2639  34055256     11

In [113]:
song_list

array(['2939095', '32939042', '32939046', '32939001', '32939000',
       '34476749', '35944240', '34055256', '33369437', '35757422'],
      dtype='<U12')

In [114]:
df[df.songId.isin(song_list)][['songId', 'title', 'artist', 'genre',]]

songId               title                     artist        genre
4588  32939046  여기저기거기 (Feat. 수퍼비)                         범키     R&B/Soul
4896  34055256           김철수 씨 이야기                        허회경  인디음악 포크/블루스
4926   2939095               널 생각해  원 모어 찬스 (one more chance)  인디음악 포크/블루스
4994  32939042            아침만 남겨주고                        김현창  인디음악 포크/블루스

In [205]:
# 해당 songId 들 정보 출력
# 나중에 to_dict()로 반환
# 없으면 플레이리스트2에 있는 songId 에서 정보 가져오기
tmp = df[df.songId.isin(song_list)][['songId', 'title', 'artist', 'genre', 'album', 'lyricist', 'composer']]
if tmp.empty:
    tmp = plist2[plist2.songId.isin(song_list)]
tmp

Empty DataFrame
Columns: [songId, title, artist, img]
Index: []